version: '3.7'

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups

